[package]
name = "netbricks"
version = "0.2.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>", "William of Ockham <williamofockham@gmail.com>"]
build = "build.rs"

[lib]
doctest = false

[dependencies]
libc = ">= 0.2.4"
time = ">=0.1.0"
getopts = "*"
byteorder = "*"
clippy = { version = ">=0.0.197", optional = true }
fnv = "*"
twox-hash = "*"
regex = "*"
lazy_static = "*"
net2 = "*"
# NIX restricts us to just unix for now, we can fix this if someone cares at a later point.
nix = "*"
# Figure out if we want this permanently or just for now.
rust-sctp = { git="https://github.com/netsys/rust-sctp", optional = true}
toml = "*"
serde = "1.0"
serde_derive = "1.0"
# Hack for SHM
uuid = { version = "*", features=["v4"] }
error-chain = "*"
num = "0.1"
num-derive="0.2"
num-traits = "0.2"
generic-array = ">=0.11.0"
crossbeam = ">=0.3.2"

[features]
default = []
performance = []
dev = ["clippy"]
packet_offset = []
sctp = ["rust-sctp"]

[build-dependencies]
# Use Bindgen to generate DPDK structures.
bindgen = "0.35.0"
