[package]
name = "echo-reply"
version = "0.1.0"
authors = ["William of Ockham <Occam_Engineering@comcast.com>"]

[dependencies]
netbricks = { path = "../../framework"}

[features]
default = []
print = []
